config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root to: "home#index"
  resources :users do
    resources :images
  end
  resources :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title

  has_attached_file :attachment, :styles => { :thumb => "250x250>", :medium => "800x800>" }
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  validates_presence_of :username


  def timeRegistered
    time_elapsed = (Time.now - self.created_at).to_i
    if time_elapsed < 60
      time_unit = "seconds"
    elsif time_elapsed < 3600
      time_unit = "minutes"
      time_elapsed = (time_elapsed/60).to_i
    elsif time_elapsed < 86400
      time_unit = "hours"
      time_elapsed = (time_elapsed/3600).to_i
    else
      time_unit = "days"
      time_elapsed = (time_elapsed/86400).to_i
    end
    "#{time_elapsed} #{time_unit}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Devise Stuff
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :username) }
  end
  # End Devise Stuff
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @images = Image.all
  end
  def show
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    # @user = User.find(params[:user_id])
    @image = Image.new()
  end
  def create
    # @user = User.find(params[:user_id])
    @image = current_user.images.new(image_params)
    if @image.save
      flash[:notice] = "Emaje uploaded. Congrats!"
      redirect_to image_path(@image)
    else
      flash[:alert] = "You shall not upload!!!"
      redirect_to :back
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  def destroy
    @image = Image.find(params[:id])
    if current_user.id == @image.user_id
      @image.destroy
      flash[:notice] = "errrh nerrrrr. deleterrrd."
      redirect_to '/'
    else
      flash[:alert] = "NERp./"
      redirect_to :back
    end
  end

  private
  def image_params
    params.require(:image).permit(:title, :description, :attachment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @images = @user.images.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h3>Le Ermajes</h3>

    <div class="images">
    <% @images.each do |image| %>
    <div class="wrapper">
        <div class="col-md-3 image-sizing">
          <a href="<%= image_path(image)%>"><%= image_tag(image.attachment.url(:thumb), size: "255x255") %></a>
        </div>
      <% end %>
    </div>
  </div>

app/views/images/new.html.erb
<h2>erhmagerd. erplerd an emaje.</h2>

<div class="forms">
  <%= simple_form_for [@image], :url => user_images_path, :html => { :multipart => true } do |form| %>

    <%= form.input :title %>
    <%= form.input :description %>
    <%= form.file_field :attachment %>
    <div id="submit">
      <%= form.submit :'Upload Image', class: "btn btn-success" %>
    </div>
<% end %>
</div>

app/views/images/show.html.erb
<h3><%= @image.title %></h3>
<p><%= link_to 'Back', root_path %></p>
<%= image_tag(@image.attachment.url(), height: '750') %>

<% if current_user %>
<% if current_user.id == @image.user_id  %>
  <p><%= link_to 'Delete', image_path(@image),
        :data => {:confirm => "Err yer shuuurrr?",
                  :method  => "delete"}%> |
  <%= link_to "Edit", edit_image_path %></p>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emajurh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top" role='navigation'>
      <ul class='nav navbar-nav'>
        <li id="logo"><%= link_to "emajurh", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Upload emaje", new_user_image_path(current_user) %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to "#{current_user.username}", user_path(current_user) %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>

    <div id="main">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h3>This is your account: <%= @user.username %></h3>

<p>Your account was created <%= @user.timeRegistered %> ago. </p>
<p>You've uploaded <%= @user.images.length %> emajes to the gallery</p>

<% if @images.any? %>
  <% @images.each do |image| %>
    <a href="<%= image_path(image)%>"><%= image_tag image.attachment.url(:thumb) %></a>
  <% end %>
<% end %>